# Generated by Django 4.0.1 on 2022-02-15 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_watchlist_avg_rating_watchlist_number_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='updated_on',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='created_on',
            new_name='created',
        ),
    ]
